// Environment sprites: foliage (procedural), props and particles (ASCII).
import { paintFoamFrame, paintWaterFrame } from '../tiles'
import type { Legend, SpriteDef } from '../pixel'
import {
  K,
  paintBeam,
  paintBush,
  paintCloudShadow,
  paintDot,
  paintGlow,
  paintPacket,
  paintPalm,
  paintPine,
  paintRipple,
  paintRock,
  paintStrip,
  paintTree,
} from '../procedural'

const WOOD: Legend = { w: 'wood', W: 'woodLight', d: 'woodDark', m: 'metalDark', M: 'metalLight', y: 'windowNight', g: 'glassLight', k: 'ink', s: 'stone' }

const proc = (name: string, w: number, h: number, paint: SpriteDef['paint'], anchor?: [number, number]): SpriteDef => ({
  name,
  w,
  h,
  legend: {},
  paint,
  anchor,
})

const strip = (name: string, w: number, h: number, frames: number, paint: SpriteDef['paint'], anchor: [number, number]): SpriteDef => ({
  name,
  w,
  h,
  frames,
  legend: {},
  paint,
  anchor,
})

const ascii = (name: string, rows: string[], legend: Legend, opts: Partial<SpriteDef> = {}): SpriteDef => ({
  name,
  rows,
  legend,
  outline: 'outline',
  ...opts,
})

export const ENV_DEFS: SpriteDef[] = [
  // ---- foliage (procedural) ----
  proc('tree_0', 32, 40, (r) => paintTree(r, 0), [16, 38]),
  proc('tree_1', 32, 40, (r) => paintTree(r, 1), [16, 38]),
  proc('pine_0', 24, 40, (r) => paintPine(r, 0), [12, 38]),
  proc('pine_1', 24, 40, (r) => paintPine(r, 1), [12, 38]),
  proc('palm_0', 32, 48, (r) => paintPalm(r, 0), [16, 46]),
  proc('palm_1', 32, 48, (r) => paintPalm(r, 1), [16, 46]),
  proc('bush_0', 20, 16, (r) => paintBush(r, 0), [10, 15]),
  proc('bush_1', 20, 16, (r) => paintBush(r, 1), [10, 15]),
  proc('rock_0', 20, 16, (r) => paintRock(r, 0), [10, 15]),
  proc('rock_1', 20, 16, (r) => paintRock(r, 1), [10, 15]),

  // ---- flowers ----
  ...(['pink', 'yellow', 'purple', 'white'] as const).map((c, i) =>
    ascii(
      `flower_${i}`,
      ['...p....', '..ppp...', '.ppYpp..', '..ppp...', '...p....', '...g....', '..gg....', '...g....'],
      { p: c, Y: i === 1 ? 'orange' : 'yellow', g: 'grassDeep' },
      { outline: undefined, anchor: [4, 8] },
    ),
  ),
  ascii(
    'flowerbed',
    [
      '................',
      '...p..y...w..p..',
      '..ppp.yyy.www.pp',
      '.DDpDDDyDDDwDDpD',
      '.DDDDDDDDDDDDDDD',
      '..DDDDDDDDDDDDD.',
    ],
    { p: 'pink', y: 'yellow', w: 'white', D: 'dirt' },
    { anchor: [8, 6] },
  ),

  // ---- tall grass (2-frame sway) ----
  ascii(
    'grass_tall',
    [
      '................................',
      '..d....d..........d....d........',
      '..d...dd....d.....d...dd....d...',
      '.dd..ddd...dd......dd..ddd...dd.',
      '.dd..dd...dd.d.....dd..dd...dd.d',
      '.ddd.dd.d.dd.d.....ddd.dd.d.dd.d',
      '.ddDddd.d.dddd.....ddDddd.d.dddd',
      '..DDDDDDDDDDD.......DDDDDDDDDDD.',
      '..DDDDDDDDDD.........DDDDDDDDDD.',
      '...DDDDDDDD...........DDDDDDDD..',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
    ],
    { d: 'grassDeep', D: 'moss' },
    { outline: undefined, frames: 2, anchor: [8, 10] },
  ),

  // ---- fences ----
  ascii(
    'fence_h',
    [
      '................',
      '..ddd...........',
      '..wWd...........',
      '..wWd...........',
      'WWWWWWWWWWWWWWWW',
      'wwwwwwwwwwwwwwww',
      '..wWd...........',
      '..wWd...........',
      'WWWWWWWWWWWWWWWW',
      'wwwwwwwwwwwwwwww',
      '..wWd...........',
      '..wWd...........',
      '..ddd...........',
      '................',
      '................',
      '................',
    ],
    WOOD,
    { anchor: [8, 13] },
  ),
  ascii(
    'fence_v',
    [
      '......ddd.......',
      '......wWd.......',
      '......wWd.......',
      '....WWwWdWW.....',
      '....wwwWdww.....',
      '......wWd.......',
      '......wWd.......',
      '......wWd.......',
      '......wWd.......',
      '....WWwWdWW.....',
      '....wwwWdww.....',
      '......wWd.......',
      '......wWd.......',
      '......wWd.......',
      '......ddd.......',
      '................',
    ],
    WOOD,
    { anchor: [8, 15] },
  ),
  ascii(
    'fence_post',
    ['......ddd.......', '......wWd.......', '......wWd.......', '......wWd.......', '......wWd.......', '......wWd.......', '......wWd.......', '......wWd.......', '......wWd.......', '......wWd.......', '......wWd.......', '......wWd.......', '......ddd.......', '................', '................', '................'],
    WOOD,
    { anchor: [8, 13] },
  ),

  // ---- lamp post (glass lights up at night via a separate glow) ----
  ascii(
    'lamp',
    [
      '.......m........',
      '......mmm.......',
      '.....mmmmm......',
      '.....mgggm......',
      '.....mgggm......',
      '.....mgggm......',
      '.....mgggm......',
      '.....mmmmm......',
      '......mmm.......',
      '.......m........',
      '.......m........',
      '......mmm.......',
      '.......m........',
      '.......m........',
      '.......m........',
      '.......m........',
      '.......m........',
      '.......m........',
      '.......m........',
      '.......m........',
      '.......m........',
      '.......m........',
      '.......m........',
      '.......m........',
      '.......m........',
      '.......m........',
      '.......m........',
      '.......m........',
      '.......m........',
      '.......m........',
      '.......m........',
      '.......m........',
      '.......m........',
      '.......m........',
      '......mmm.......',
      '.....mmmmm......',
      '....mmmmmmm.....',
      '................',
      '................',
      '................',
    ],
    { m: 'metalDark', g: 'glassLight' },
    { anchor: [8, 37] },
  ),
  ascii(
    'lamp_lit',
    ['.....yyy......', '....yYYYy.....', '....yYYYy.....', '....yYYYy.....', '.....yyy......'],
    { y: 'yellow', Y: 'glowWarm' },
    { outline: undefined, anchor: [7, 2] },
  ),

  // ---- signpost ----
  ascii(
    'signpost',
    [
      '........................',
      '......WWWWWWWWWWWWWWW...',
      '......wkkkwkkwwkkkkwwW..',
      '......wwwwwwwwwwwwwwwwW.',
      '......wkkwwkkkwkkwwwwwW.',
      '......ddddddddddddddddd.',
      '..........wWd...........',
      '..........wWd...........',
      '..WWWWWWWWWWWWWWW.......',
      '.WwwkkwkkkwwkkwwW.......',
      'Wwwwwwwwwwwwwwwww.......',
      '.Wwwkkkwwkkwwkkww.......',
      '..ddddddddddddddd.......',
      '..........wWd...........',
      '..........wWd...........',
      '..........wWd...........',
      '..........wWd...........',
      '..........wWd...........',
      '..........wWd...........',
      '..........wWd...........',
      '..........wWd...........',
      '..........wWd...........',
      '..........wWd...........',
      '.........ddddd..........',
      '........................',
      '........................',
    ],
    WOOD,
    { anchor: [12, 24] },
  ),
  ascii(
    'sign_small',
    [
      '................',
      '.WWWWWWWWWWWWWW.',
      '.wwkkkwkkwkkkww.',
      '.wwwwwwwwwwwwww.',
      '.wwkkwkkkwkkwww.',
      '.wwwwwwwwwwwwww.',
      '.dddddddddddddd.',
      '......wWd.......',
      '......wWd.......',
      '......wWd.......',
      '......wWd.......',
      '......wWd.......',
      '.....ddddd......',
      '................',
      '................',
      '................',
    ],
    WOOD,
    { anchor: [8, 13] },
  ),

  // ---- bench ----
  ascii(
    'bench',
    [
      '.WWWWWWWWWWWWWWWWWWWWWW.',
      '.wwwwwwwwwwwwwwwwwwwwww.',
      '.dddddddddddddddddddddd.',
      '.WWWWWWWWWWWWWWWWWWWWWW.',
      '.wwwwwwwwwwwwwwwwwwwwww.',
      '.dddddddddddddddddddddd.',
      '..mm................mm..',
      '..mm................mm..',
      '..mm................mm..',
      '..mm................mm..',
      '........................',
      '........................',
    ],
    WOOD,
    { anchor: [12, 10] },
  ),

  // ---- small things ----
  ascii('shell_0', ['..ppp...', '.pcpcp..', 'pcpcpcp.', '.ppppp..', '..ppp...', '........'], { p: 'pink', c: 'cream' }, { anchor: [4, 5] }),
  ascii('shell_1', ['..www...', '.wcwcw..', 'wcwcwcw.', '.wwwww..', '..w.w...', '........'], { w: 'white', c: 'creamDark' }, { anchor: [4, 5] }),
  ascii('mushroom_0', ['..rrrr..', '.rwrrwr.', 'rrrrrrrr', '.rwrrrr.', '...cc...', '...cc...', '...cc...', '..cccc..'], { r: 'red', w: 'white', c: 'cream' }, { anchor: [4, 8] }),
  ascii('mushroom_1', ['..bbbb..', '.bbbbbb.', 'bbbbbbbb', '...cc...', '...cc...', '..cccc..', '........', '........'], { b: 'wood', c: 'cream' }, { anchor: [4, 6] }),
  ascii(
    'stump',
    ['....WWWWWWWW....', '..WWwwwWWwwwWW..', '.WwwWWwwwwWWwwW.', '.WwwwwwwwwwwwwW.', '.ddwwwwwwwwwwdd.', '.ddddddddddddd..', '.dddddddddddddd.', '.dddddddddddddd.', '..dddddddddddd..', '................', '................', '................'],
    WOOD,
    { anchor: [8, 9] },
  ),
  ascii(
    'log',
    ['.WWWWWWWWWWWWWWWWWW.', 'WwwwwwwwwwwwwwwwwwwW', 'WwwwwwwwwwwwwwwwwwwW', 'WddddddddddddddddddW', '.dddddddddddddddddd.', '....................', '....................', '....................', '....................', '....................'],
    WOOD,
    { anchor: [10, 5] },
  ),
  ascii('lily_0', ['..gggg..', '.gggggg.', 'gggg.ggg', 'ggggg.gg', '.gggggg.', '..gggg..'], { g: 'leaf' }, { outline: undefined, anchor: [4, 3] }),
  ascii('lily_1', ['..gpgg..', '.gpppgg.', 'gggpgggg', 'ggggg.gg', '.gggggg.', '..gggg..'], { g: 'leaf', p: 'pink' }, { outline: undefined, anchor: [4, 3] }),
  ascii(
    'reed_0',
    ['..b...b.', '..b...b.', '..g...g.', '..g.b.g.', '..g.b.g.', '.gg.g.gg', '.g..g..g', '.g..g..g', 'gg..g..g', 'g...g..g', 'g..gg.gg', 'g..g..g.', '....g...', '........', '........', '........'],
    { g: 'moss', b: 'wood' },
    { outline: undefined, anchor: [4, 13] },
  ),
  ascii(
    'reed_1',
    ['....b...', '..b.b...', '..b.g...', '..g.g...', '..g.g.b.', '..g.g.g.', '.gg.g.g.', '.g..g.g.', '.g.gg.g.', 'gg.g..g.', 'g..g.gg.', 'g..g.g..', '....g...', '........', '........', '........'],
    { g: 'moss', b: 'wood' },
    { outline: undefined, anchor: [4, 13] },
  ),

  // ---- chest ----
  ascii(
    'chest_closed',
    ['..WWWWWWWWWWWW..', '.WwwwwwwwwwwwwW.', '.mwwwwwwwwwwwwm.', '.mmmmmmmmmmmmmm.', '.wwwwwwmywwwwww.', '.wwwwwwyywwwwww.', '.wwwwwwwwwwwwww.', '.wwwwwwwwwwwwww.', '.dddddddddddddd.', '.mm..........mm.', '................', '................', '................', '................'],
    { ...WOOD, y: 'yellow' },
    { anchor: [8, 10] },
  ),
  ascii(
    'chest_open',
    ['..WWWWWWWWWWWW..', '.WwwwwwwwwwwwwW.', '.wwwwwwwwwwwwww.', '.mmmmmmmmmmmmmm.', '.kkkkkkkkkkkkkk.', '.kkkkkkkkkkkkkk.', '.mwwwwwwwwwwwwm.', '.wwwwwwwwwwwwww.', '.wwwwwwwwwwwwww.', '.dddddddddddddd.', '.mm..........mm.', '................', '................', '................'],
    WOOD,
    { anchor: [8, 11] },
  ),
  ascii(
    'dock_post',
    ['.dddd.', '.wwWd.', '.wwWd.', '.wwWd.', '.wwWd.', '.wwWd.', '.wwWd.', '.wwWd.', '.wwWd.', '.wwWd.', '.dddd.', '......'],
    WOOD,
    { anchor: [3, 11] },
  ),

  // ---- collectibles, particles, fx (procedural) ----
  strip('packet', 48, 12, 4, (r) => paintPacket(r, 4), [6, 6]),
  proc('mote', 4, 4, (r) => paintDot(r, K('tealLight')), [2, 2]),
  proc('dust', 6, 6, (r) => paintDot(r, [230, 214, 170, 220]), [3, 3]),
  proc('spark', 4, 4, (r) => paintDot(r, [255, 247, 200, 255]), [2, 2]),
  proc('star', 3, 3, (r) => paintDot(r, [255, 255, 240, 230]), [1, 1]),
  proc('leaf', 4, 3, (r) => paintDot(r, K('leafLight')), [2, 1]),
  proc('rain', 2, 11, (r) => paintDot(r, [208, 235, 255, 215]), [1, 5]),
  proc('firefly', 3, 3, (r) => paintDot(r, [255, 240, 140, 255]), [1, 1]),
  strip('ripple', 36, 6, 3, (r) => paintRipple(r), [6, 3]),
  proc('light_soft', 64, 64, (r) => paintGlow(r, [255, 255, 255, 255], 1.4), [32, 32]),
  proc('glow_warm', 48, 48, (r) => paintGlow(r, [255, 205, 120, 255], 2.2), [24, 24]),
  proc('glow_cool', 32, 32, (r) => paintGlow(r, [150, 240, 220, 255], 2), [16, 16]),
  proc('cloud_shadow', 128, 96, (r) => paintCloudShadow(r), [64, 48]),
  proc('beam', 160, 48, (r) => paintBeam(r), [0, 24]),
  strip('water', 256, 64, 4, (r) => paintStrip(r, 4, (rr, ox, f) => paintWaterFrame(rr, ox, 0, f)), [0, 0]),
  strip('foam', 64, 16, 4, (r) => paintStrip(r, 4, (rr, ox, f) => paintFoamFrame(rr, ox, 0, f)), [8, 8]),
]
